feedback duplicado bloqueado
ignacioct-ey/ElypseIC pull request #244
Opened 2024-09-24 15:20 UTC by Tanvir-EY

Tarea 521: 

Antes en el user interface de iArte se podía dar varios feedbacks por cada output. Eso era un fallo y se pidio cambios. He modificado varios archivos de frontend y ahora solo se puede dar feedback una vez por output, ya sea positivo o negativo.

2024-09-24 16:10 UTC, ignacioct-ey reviewed
Manana la probare en pantalla grande para ver que todo este bien colocado, de momento aqui van un par de cuestiones

2024-09-24 16:10 UTC, ignacioct-ey commented on frontend/src/components/LikeDislike/Buttons/DislikeButton.tsx
> +interface PropsData {
por que has renombrado esta variable?

2024-09-24 16:10 UTC, ignacioct-ey commented on frontend/src/components/LikeDislike/Buttons/LikeButton.tsx
> +interface PropsData {
misma pregunta

2024-09-24 16:10 UTC, ignacioct-ey commented on frontend/src/components/LikeDislike/Modals/ModalLikeButton.tsx
> +                <textarea name="like-comments" aria-label="Comments for improvement" />
No es necesario un aria-label, y menos en ingles

2024-09-24 16:21 UTC, Tanvir-EY commented on frontend/src/components/LikeDislike/Modals/ModalLikeButton.tsx
> +                <textarea name="like-comments" aria-label="Comments for improvement" />
lo quito ahora

2024-09-24 16:27 UTC, Tanvir-EY commented on frontend/src/components/LikeDislike/Buttons/DislikeButton.tsx
> +interface PropsData {
Al cambiarlo fue un cambio de propsData a PropsData, no fue por ninguna razón más excepto utilizar upper camel case naming. Los nombres de los archvos están puestos así, p.e. DislikeButton.tsx

2024-09-24 16:27 UTC, Tanvir-EY commented on frontend/src/components/LikeDislike/Buttons/LikeButton.tsx
> +interface PropsData {
Al cambiarlo fue un cambio de propsData a PropsData, no fue por ninguna razón más excepto utilizar upper camel case naming. Los nombres de los archvos están puestos así, p.e. LikeButton.tsx

2024-09-24 16:50 UTC, Tanvir-EY commented on frontend/src/components/LikeDislike/Modals/ModalLikeButton.tsx
> +                <textarea name="like-comments" aria-label="Comments for improvement" />
he quitado esa linea

2024-09-25 13:12 UTC, ignacioct-ey requested changes
Hay un fallo en el boton X para cerrar la pantalla de feedback, aparece en la mitad del modal 
![image](https://github.com/user-attachments/assets/ce2aaff8-29ea-47de-a81c-34ef851f5427)
![image](https://github.com/user-attachments/assets/fbc660be-98a0-40b3-90b2-746537af2d46)

En la primera imagen aparece en el primer cuadro de texto, en la segunda ni aparece. El close modal debe de haberse descuadrado

2024-09-27 07:39 UTC, ignacioct-ey requested changes
yo lo sigo viendo mal
![image](https://github.com/user-attachments/assets/a460b54c-f02a-454a-adb0-2141cea16d54)
![image](https://github.com/user-attachments/assets/ea8a21b3-9324-4129-916c-82fb681c10da)

2024-09-27 07:47 UTC, ignacioct-ey approved these changes
fallo mio en la anterior, la veo bien

2024-09-27 07:56 UTC, merged